name: switch
on:
  push:
    branches:
      - master
      - feature/gh-actions-switch
    tags:
      - '*'
  pull_request: {}
  workflow_dispatch:

jobs:
  build_switch:
    name: Build Switch
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: "./stk-code"
      - name: Checkout OpenAL
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: "./stk-code/lib/openal"
          repository: "kcat/openal-soft"
      - name: Checkout Harfbuzz
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: "./stk-code/lib/harfbuzz"
          repository: "harfbuzz/harfbuzz"
      - name: Grab assets
        run: |
          sudo apt update
          sudo apt install unzip -y
          wget -q https://github.com/supertuxkart/stk-assets-mobile/releases/download/git/stk-assets-full.zip
          unzip -q stk-assets-full.zip -d stk-assets
          rm stk-assets-full.zip
      - name: [Hack] Copy Cmake toolchain into /opt/devkitpro
        run: |
          cp -v stk-code/switch/pkgbuild-scripts/* "$DEVKITPRO/"
      - name: Run build script
        run: |
          cd stk-code/switch
          sudo PROJECT_VESION=$release_tag bash ./make.sh
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/SuperTuxKart-${{ env.release_tag }}-switch.zip"
          tag: ${{ env.release_name }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          allowUpdates: true
          prerelease: ${{ env.release_pre }}

